chore: refactored kitty settings

diff --git a/dot_functions b/dot_functions
--- a/dot_functions
+++ b/dot_functions
@@ -42,3 +42,20 @@ function activate() {
 	done
 	source $1/bin/activate
 }
+
+function logcat {
+	pkg="$1"
+	shift
+	if [ -z "$pkg" ]; then
+		>&2 echo 'Usage: logcat pkg ...'
+		return 1
+	fi
+
+	uid="$(adb shell pm list package -U $pkg | sed 's/.*uid://')"
+	if [ -z "$uid" ]; then
+		>&2 echo "pkg '$pkg' not found"
+		return 1
+	fi
+
+	adb logcat --uid="$uid" "$@"
+}
